#!/bin/bash --login
#PBS -N sc3lr
#PBS -l select=8


#PBS -l walltime=23:30:00


#PBS -A n01-Marshall3

export PBS_O_WORKDIR=$(readlink -f /work/n01/n01/forshaw/dat/sc3lr)


cd /work/n01/n01/forshaw/dat/sc3lr

export OMP_NUM_THREADS=1

export MPICH_FAST_MEMCPY=1
export MPICH_COLL_OPT_ON=1
export MPICH_ENV_DISPLAY=1


#export PAT_RT_SUMMARY=0

#module add perftools

aprun -n 192  -N 24 ./sw.out

#qsub copyscript
