#!/bin/bash --login
#PBS -N t3l
#PBS -l select=1


#PBS -l walltime=47:30:00
#PBS -q long


#PBS -A n01-Marshall3

export PBS_O_WORKDIR=$(readlink -f /work/n01/n01/forshaw/dat/t3l)


cd /work/n01/n01/forshaw/dat/t3l

export OMP_NUM_THREADS=1

export MPICH_FAST_MEMCPY=1
export MPICH_COLL_OPT_ON=1
export MPICH_ENV_DISPLAY=1


#export PAT_RT_SUMMARY=0

#module add perftools

aprun -n 24  -N 24 ./sw.out

#qsub copyscript
